MySql.QueryTools.WebApp/Models/ErrorViewModel.cs
namespace MySql.QueryTools.WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MySql.QueryTools.WebApp/Models/QueryViewModel.cs
using System.Collections;

namespace MySql.QueryTools.WebApp.Models
{
    public class QueryViewModel
    {
        public string Query { get; set; }
        public ArrayList Headers { get; set; }
        public ArrayList Items { get; set; }
        public string Error { get; set; }
    }
}

MySql.QueryTools.WebApp/Controllers/AboutController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace MySql.QueryTools.WebApp.Controllers
{
    public class AboutController : Controller
    {
        private readonly ILogger<AboutController> _logger;

        public AboutController(ILogger<AboutController> logger)
        {
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            return await Task.FromResult(View());
        }
    }
}

MySql.QueryTools.WebApp/Controllers/HomeController.cs
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MySql.QueryTools.WebApp.Models;

namespace MySql.QueryTools.WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public async Task<IActionResult> Error()
        {
            return await Task.FromResult(View(new ErrorViewModel
                { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier }));
        }
    }
}

MySql.QueryTools.WebApp/Controllers/QueryController.cs
using System;
using System.Collections;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using MySql.Data.MySqlClient;
using MySql.QueryTools.WebApp.Models;

namespace MySql.QueryTools.WebApp.Controllers
{
    public class QueryController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly ILogger<QueryController> _logger;

        public QueryController(IConfiguration configuration, ILogger<QueryController> logger)
        {
            _configuration = configuration;
            _logger = logger;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string q)
        {
            if (string.IsNullOrEmpty(q)) return await Task.FromResult(View());

            _logger.LogTrace($"Execute query '{q}'");

            var model = new QueryViewModel
            {
                Query = q
            };

            try
            {
                model.Items = new ArrayList();
                model.Headers = new ArrayList();

                await using var connection =
                    new MySqlConnection(_configuration.GetConnectionString("SphinxConnection"));
                await connection.OpenAsync();
                await using (var command = new MySqlCommand(model.Query, connection))
                {
                    await using var reader = command.ExecuteReader();
                    var first = true;
                    while (reader.Read())
                    {
                        var row = new ArrayList();
                        for (var i = 0; i < reader.FieldCount; i++) row.Add(reader.GetValue(i));
                        if (first)
                            for (var i = 0; i < reader.FieldCount; i++)
                                model.Headers.Add(reader.GetName(i));
                        model.Items.Add(row);
                        first = false;
                    }
                }

                await connection.CloseAsync();
                _logger.LogInformation($"Success execute query '{q}'. Returns {model.Items.Count} records.");
            }
            catch (Exception ex)
            {
                model.Error = ex.Message;
                _logger.LogError($"Error while execute query '{q}'. {ex.Message}");
            }

            return await Task.FromResult(View(model));
        }
    }
}

MySql.QueryTools.WebApp/Views/About/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <p>QueryTools is designed to perform queries in the Sphinx Search or Manticore Search using the MySQL adapter.</p>
    <ul class="text-justify">
        <li><a href="http://sphinxsearch.com/" target="_blank">Sphinx</a> is an open source full text search server, designed from the ground up with performance, relevance (aka search quality), and integration simplicity in mind. It's written in C++ and works on Linux (RedHat, Ubuntu, etc), Windows, MacOS, Solaris, FreeBSD, and a few other systems.</li>
        <li><a href="https://manticoresearch.com/" target="_blank">Manticore Search</a> was born in 2017 as a continuation of Sphinx Search (which started in 2001). We took the best from Sphinx (C++ core and focus on low level data structures and fine-tuned algorithms), added more functionality, fixed tons of bugs, made it easier to use, kept it open source and made Manticore Search even more lightweight & extremely fast full-text search engine.</li>
    </ul>
</div>

MySql.QueryTools.WebApp/Views/Query/Index.cshtml
@using System.Collections
@model MySql.QueryTools.WebApp.Models.QueryViewModel

@{
    ViewData["Title"] = "Query Page";
}

<div class="text-center">
    @using (Html.BeginForm("Index", "Query", FormMethod.Get, new { onsubmit = "return onSubmitHandler(this);" }))
    {
        @Html.Hidden("q")
        <pre id="editor" style="height: 5em;">@Model?.Query</pre>
        <script src="~/lib/ace-builds-master/src/ace.js"></script>
        <script src="~/lib/ace-builds-master/src/theme-github.js"></script>
        <script src="~/lib/ace-builds-master/src/mode-sql.js"></script>
        <script>
            editor = ace.edit("editor");
            editor.setTheme("ace/theme/github");
            editor.session.setMode("ace/mode/sql");
            document.getElementById("editor").style.fontSize = "1.25em";
        </script>
        <p>
            <input type="submit"/>
        </p>
    }
    <script>
        function onSubmitHandler(form) {
            document.getElementById("q").value = editor.getValue();
            return true;
        }
    </script>

    @if (Model?.Items != null)
    {
        <div id="wrapper"></div>
        <link href="~/lib/gridjs/dist/theme/mermaid.min.css" rel="stylesheet" />
        <script src="~/lib/gridjs/dist/gridjs.umd.js"></script>
        <script>
            var columns = [];

            @foreach (var d in Model.Headers)
            {
                @:columns.push({ name: "@d", formatter: (cell) => gridjs.html(cell)});
            }
            var data = [];

            @foreach (var r in Model.Items)
            {
                @:var row = [];

                @foreach (var d in (ArrayList)r)
                {
                    @:row.push("@d");
                }
                @:data.push(row);
            }

            new gridjs.Grid({
                columns: columns,
                data: data,
                height: "calc(100vh - 25em)"
            }).render(document.getElementById("wrapper"));
        </script>
    }

    <div style="height: 2em; overflow: auto; width: 100%;">
        @Html.DisplayTextFor(m => m.Error)
    </div>
</div>

MySql.QueryTools.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - QueryTools</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Query" asp-action="Index">QueryTools</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Query" asp-action="Index">Query</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="Index">About</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - QueryTools
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", false)
</body>
</html>